graph [
 comment "Graph generated by CoGNaC"
 directed 1
 node [
  id 1
  label "1"
  cell_cycle_length 108.408
  graphics [
   x 0
   y 0
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "1"
  ]
 ]
 node [
  id 2
  label "2"
  cell_cycle_length 113
  graphics [
   x 80
   y 0
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "2"
  ]
 ]
 node [
  id 3
  label "3"
  cell_cycle_length 4
  graphics [
   x 0
   y 80
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "3"
  ]
 ]
 node [
  id 4
  label "4"
  cell_cycle_length 29
  graphics [
   x 80
   y 80
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "4"
  ]
 ]
 edge [
  source 1
  target 2
  label " "
  probability 0.945974
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 1
  target 3
  label " "
  probability 0.0518657
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 1
  target 4
  label " "
  probability 0.00216022
  graphics [
   arrow "last"
  ]
 ]
]