graph [
 comment "Graph generated by Chaste"
 directed 1
 node [
  id 1
  label "1"
  graphics [
   x 0
   y 0
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "1"
  ]
 ]
 node [
  id 2
  label "2"
  graphics [
   x 80
   y 0
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "2"
  ]
 ]
 node [
  id 3
  label "3"
  graphics [
   x 160
   y 0
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "3"
  ]
 ]
 node [
  id 4
  label "4"
  graphics [
   x 240
   y 0
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "4"
  ]
 ]
 node [
  id 5
  label "5"
  graphics [
   x 0
   y 80
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "5"
  ]
 ]
 node [
  id 6
  label "6"
  graphics [
   x 80
   y 80
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "6"
  ]
 ]
 node [
  id 7
  label "7"
  graphics [
   x 160
   y 80
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "7"
  ]
 ]
 node [
  id 8
  label "8"
  graphics [
   x 240
   y 80
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "8"
  ]
 ]
 node [
  id 9
  label "9"
  graphics [
   x 0
   y 160
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "9"
  ]
 ]
 node [
  id 10
  label "10"
  graphics [
   x 80
   y 160
   w 40.0
   h 40.0
   type "ellipse"
  ]
  LabelGraphics [
   text "10"
  ]
 ]
 edge [
  source 1
  target 1
  label "1 -> 1"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 3
  target 2
  label "3 -> 2"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 4
  target 2
  label "4 -> 2"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 1
  target 3
  label "1 -> 3"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 2
  target 3
  label "2 -> 3"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 5
  target 3
  label "5 -> 3"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 6
  target 3
  label "6 -> 3"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 10
  target 3
  label "10 -> 3"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 3
  target 4
  label "3 -> 4"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 5
  target 4
  label "5 -> 4"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 6
  target 4
  label "6 -> 4"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 10
  target 4
  label "10 -> 4"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 3
  target 5
  label "3 -> 5"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 4
  target 5
  label "4 -> 5"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 5
  target 5
  label "5 -> 5"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 7
  target 5
  label "7 -> 5"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 8
  target 5
  label "8 -> 5"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 9
  target 5
  label "9 -> 5"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 1
  target 6
  label "1 -> 6"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 2
  target 6
  label "2 -> 6"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 5
  target 6
  label "5 -> 6"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 6
  target 6
  label "6 -> 6"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 10
  target 6
  label "10 -> 6"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 10
  target 7
  label "10 -> 7"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 5
  target 8
  label "5 -> 8"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 7
  target 8
  label "7 -> 8"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 8
  target 8
  label "8 -> 8"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 9
  target 8
  label "9 -> 8"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 10
  target 8
  label "10 -> 8"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 5
  target 9
  label "5 -> 9"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 6
  target 9
  label "6 -> 9"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 7
  target 9
  label "7 -> 9"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 10
  target 9
  label "10 -> 9"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 7
  target 10
  label "7 -> 10"
  graphics [
   arrow "last"
  ]
 ]
 edge [
  source 9
  target 10
  label "9 -> 10"
  graphics [
   arrow "last"
  ]
 ]
]